<EntryLayout>

    GridLayout:
        cols:1
        size: root.width, root.height

        GridLayout:
            cols:2

            Label:
                text: "Date"
            TextInput:
                multiline: False
            
            Label:
                text: "Reason 1"
            TextInput:
                multiline: False
        
        Button:
            text: "Submit"
            font_size:32
        
